# Use root/example as user/password credentials
version: '3.1'

services:

 # mongo:
 #   image: mongo
 #   restart: always
 #   environment:
 #     MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: userdb
      ME_CONFIG_MONGODB_ADMINPASSWORD: ma292827
      ME_CONFIG_MONGODB_URL: mongodb+srv://userdb:ma292827@cluster0.cwhtn.mongodb.net/test